### ISSUE TITLE
Deep learning ray traced lightmapped SIMD accelerated system for computation of SSAO using layered MSAA on TAA background framebuffer, with high FOV resolution cubemapped phong CSG spheres with inverted SRGB PNG TGA ICO images

### ISSUE THREAD

**Issue by JJL772** [Spirrwell/Mod-Engine#1]
Will this feature be added???

**Comment by Spirrwell** [comment]
![image](https://user-images.githubusercontent.com/8671884/77818154-9aaafa80-70a6-11ea-95c1-90ab46160620.png)

**Comment by JJL772** [comment]
oh my god
is that the matrix????

**Comment by Spirrwell** [comment]
It's my desktop from 2011. Figured it makes about as much sense as this feature request lol

**Comment by JJL772** [comment]
omg...are you running KALI LINUX?????
